name: 'Cocos Creator Build updated'
description: 'A github action for cocos creator build'
author: 'miggene'
branding:
  icon: activity
  color: blue
inputs:
  cocos_download_url:
    required: false
    description: 'cocos creator download urls'
    default: 'https://creator-api.cocos.com/api/cocoshub/editor_version_list?lang=zh'

  cocos_version:
    required: false
    description: 'cocos creator version'
    default: '0.0.0'

  cocos_type:
    required: false
    description: 'cocos creator type(2d/3d)'
    default: '2d'

  project_path:
    required: false
    description: 'project path for build'
    default: './'

  platform:
    required: false
    description: 'platform to build'
    default: 'web-mobile'

  build_path:
    required: false
    description: 'build path'
    default: './build'

runs:
  using: 'node12'
  main: 'dist/index.js'
